//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18444
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NClass.CSharpSourceCodeImport.Lang {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NClass.CSharpSourceCodeImport.Lang.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à class.
        /// </summary>
        internal static string Element_Class {
            get {
                return ResourceManager.GetString("Element_Class", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Constant.
        /// </summary>
        internal static string Element_Constant {
            get {
                return ResourceManager.GetString("Element_Constant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à constructor.
        /// </summary>
        internal static string Element_Constructor {
            get {
                return ResourceManager.GetString("Element_Constructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à delegate.
        /// </summary>
        internal static string Element_Delegate {
            get {
                return ResourceManager.GetString("Element_Delegate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à elements.
        /// </summary>
        internal static string Element_Elements {
            get {
                return ResourceManager.GetString("Element_Elements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à enum.
        /// </summary>
        internal static string Element_Enum {
            get {
                return ResourceManager.GetString("Element_Enum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enum value.
        /// </summary>
        internal static string Element_EnumValue {
            get {
                return ResourceManager.GetString("Element_EnumValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à event.
        /// </summary>
        internal static string Element_Event {
            get {
                return ResourceManager.GetString("Element_Event", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à field.
        /// </summary>
        internal static string Element_Field {
            get {
                return ResourceManager.GetString("Element_Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à interface.
        /// </summary>
        internal static string Element_Interface {
            get {
                return ResourceManager.GetString("Element_Interface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à method.
        /// </summary>
        internal static string Element_Method {
            get {
                return ResourceManager.GetString("Element_Method", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Operator.
        /// </summary>
        internal static string Element_Operator {
            get {
                return ResourceManager.GetString("Element_Operator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à property.
        /// </summary>
        internal static string Element_Property {
            get {
                return ResourceManager.GetString("Element_Property", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à struct.
        /// </summary>
        internal static string Element_Struct {
            get {
                return ResourceManager.GetString("Element_Struct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Could not load assembly since it seems to be not an assembly....
        /// </summary>
        internal static string Error_BadImageFormat {
            get {
                return ResourceManager.GetString("Error_BadImageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error while importing!
        ///
        ///{0}
        ///
        ///Note: Assemblys which are created with a fuscator might fail to import..
        /// </summary>
        internal static string Error_GeneralException {
            get {
                return ResourceManager.GetString("Error_GeneralException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error.
        /// </summary>
        internal static string Error_MessageBoxTitle {
            get {
                return ResourceManager.GetString("Error_MessageBoxTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Could not open assembly due to missing referenced assemblies..
        /// </summary>
        internal static string Error_MissingReferencedAssemblies {
            get {
                return ResourceManager.GetString("Error_MissingReferencedAssemblies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No assembly file to import..
        /// </summary>
        internal static string Error_NoAssembly {
            get {
                return ResourceManager.GetString("Error_NoAssembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &amp;Import an assembly....
        /// </summary>
        internal static string Menu_Title {
            get {
                return ResourceManager.GetString("Menu_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .NET assembly importer by Malte Ried.
        /// </summary>
        internal static string Menu_ToolTip {
            get {
                return ResourceManager.GetString("Menu_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à all.
        /// </summary>
        internal static string Modifier_All {
            get {
                return ResourceManager.GetString("Modifier_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à default.
        /// </summary>
        internal static string Modifier_Default {
            get {
                return ResourceManager.GetString("Modifier_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à instance.
        /// </summary>
        internal static string Modifier_Instance {
            get {
                return ResourceManager.GetString("Modifier_Instance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à internal.
        /// </summary>
        internal static string Modifier_Internal {
            get {
                return ResourceManager.GetString("Modifier_Internal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à private.
        /// </summary>
        internal static string Modifier_Private {
            get {
                return ResourceManager.GetString("Modifier_Private", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à protected.
        /// </summary>
        internal static string Modifier_Protected {
            get {
                return ResourceManager.GetString("Modifier_Protected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à protected internal.
        /// </summary>
        internal static string Modifier_ProtectedInternal {
            get {
                return ResourceManager.GetString("Modifier_ProtectedInternal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à public.
        /// </summary>
        internal static string Modifier_Public {
            get {
                return ResourceManager.GetString("Modifier_Public", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à static.
        /// </summary>
        internal static string Modifier_Static {
            get {
                return ResourceManager.GetString("Modifier_Static", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Assemblies (*.exe, *.dll)|*.exe;*.dll.
        /// </summary>
        internal static string OpenFileDialog_Filter {
            get {
                return ResourceManager.GetString("OpenFileDialog_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cancel.
        /// </summary>
        internal static string Settings_CancelButton {
            get {
                return ResourceManager.GetString("Settings_CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Create Associations.
        /// </summary>
        internal static string Settings_CreateAssociations {
            get {
                return ResourceManager.GetString("Settings_CreateAssociations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Create Generalizations.
        /// </summary>
        internal static string Settings_CreateGeneralizations {
            get {
                return ResourceManager.GetString("Settings_CreateGeneralizations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Create a label on the side of the aggregation.
        /// </summary>
        internal static string Settings_CreateLabel {
            get {
                return ResourceManager.GetString("Settings_CreateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Create nesting Relationships.
        /// </summary>
        internal static string Settings_CreateNesting {
            get {
                return ResourceManager.GetString("Settings_CreateNesting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Create Realizations.
        /// </summary>
        internal static string Settings_CreateRealizations {
            get {
                return ResourceManager.GetString("Settings_CreateRealizations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Create Relationships.
        /// </summary>
        internal static string Settings_CreateRelationships {
            get {
                return ResourceManager.GetString("Settings_CreateRelationships", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &apos;&lt;&apos; is not allowed.
        /// </summary>
        internal static string Settings_Error_AngleBracketNotAllowed {
            get {
                return ResourceManager.GetString("Settings_Error_AngleBracketNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please enter a name.
        /// </summary>
        internal static string Settings_Error_NoTemplateName {
            get {
                return ResourceManager.GetString("Settings_Error_NoTemplateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please select a template first.
        /// </summary>
        internal static string Settings_Error_NoTemplateSelected {
            get {
                return ResourceManager.GetString("Settings_Error_NoTemplateSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à This template can&apos;t be deleted.
        /// </summary>
        internal static string Settings_Error_TemplateCantBeDeleted {
            get {
                return ResourceManager.GetString("Settings_Error_TemplateCantBeDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Import everything except.
        /// </summary>
        internal static string Settings_Filter_BlackList {
            get {
                return ResourceManager.GetString("Settings_Filter_BlackList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Element.
        /// </summary>
        internal static string Settings_Filter_ElementColumnTitle {
            get {
                return ResourceManager.GetString("Settings_Filter_ElementColumnTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Filter.
        /// </summary>
        internal static string Settings_Filter_GroupTitle {
            get {
                return ResourceManager.GetString("Settings_Filter_GroupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Modifier.
        /// </summary>
        internal static string Settings_Filter_ModifierColumnTitle {
            get {
                return ResourceManager.GetString("Settings_Filter_ModifierColumnTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Import only the folowing.
        /// </summary>
        internal static string Settings_Filter_WhiteList {
            get {
                return ResourceManager.GetString("Settings_Filter_WhiteList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à OK.
        /// </summary>
        internal static string Settings_OKButton {
            get {
                return ResourceManager.GetString("Settings_OKButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Remove fields which constructs the aggregation (code generation won&apos;t produce any code for that aggregation).
        /// </summary>
        internal static string Settings_RemoveFields {
            get {
                return ResourceManager.GetString("Settings_RemoveFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Template.
        /// </summary>
        internal static string Settings_Template {
            get {
                return ResourceManager.GetString("Settings_Template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delete.
        /// </summary>
        internal static string Settings_Template_DeleteButton {
            get {
                return ResourceManager.GetString("Settings_Template_DeleteButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &lt;last used&gt;.
        /// </summary>
        internal static string Settings_Template_LastUsed {
            get {
                return ResourceManager.GetString("Settings_Template_LastUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Load.
        /// </summary>
        internal static string Settings_Template_LoadButton {
            get {
                return ResourceManager.GetString("Settings_Template_LoadButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Store.
        /// </summary>
        internal static string Settings_Template_StoreButton {
            get {
                return ResourceManager.GetString("Settings_Template_StoreButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Import settings.
        /// </summary>
        internal static string Settings_Title {
            get {
                return ResourceManager.GetString("Settings_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Some unsafe types exist at the imported assembly. Every element using such a type isn&apos;t imported..
        /// </summary>
        internal static string UnsafeTypesPresent {
            get {
                return ResourceManager.GetString("UnsafeTypesPresent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Warning.
        /// </summary>
        internal static string WarningTitle {
            get {
                return ResourceManager.GetString("WarningTitle", resourceCulture);
            }
        }
    }
}
