//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18444
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDFExport.Lang {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PDFExport.Lang.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Could not write PDF:
        ///{0}.
        /// </summary>
        internal static string Error_CoulNotWritePDF {
            get {
                return ResourceManager.GetString("Error_CoulNotWritePDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error.
        /// </summary>
        internal static string ErrorDialog_Title {
            get {
                return ResourceManager.GetString("ErrorDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Close.
        /// </summary>
        internal static string FinishedDialog_Close {
            get {
                return ResourceManager.GetString("FinishedDialog_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Open.
        /// </summary>
        internal static string FinishedDialog_Open {
            get {
                return ResourceManager.GetString("FinishedDialog_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à PDF Export is finished. Do you want to open the exported PDF?.
        /// </summary>
        internal static string FinishedDialog_Text {
            get {
                return ResourceManager.GetString("FinishedDialog_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à PDF Exporter finished.
        /// </summary>
        internal static string FinishedDialog_Title {
            get {
                return ResourceManager.GetString("FinishedDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &amp;Export as PDF....
        /// </summary>
        internal static string Menu_Title {
            get {
                return ResourceManager.GetString("Menu_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à PDF Export by Malte Ried.
        /// </summary>
        internal static string Menu_ToolTip {
            get {
                return ResourceManager.GetString("Menu_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Bottom.
        /// </summary>
        internal static string Options_Bottom {
            get {
                return ResourceManager.GetString("Options_Bottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cancel.
        /// </summary>
        internal static string Options_CancelButton {
            get {
                return ResourceManager.GetString("Options_CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Left.
        /// </summary>
        internal static string Options_Left {
            get {
                return ResourceManager.GetString("Options_Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Margin.
        /// </summary>
        internal static string Options_Margin {
            get {
                return ResourceManager.GetString("Options_Margin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à OK.
        /// </summary>
        internal static string Options_OKButton {
            get {
                return ResourceManager.GetString("Options_OKButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Export only selected elements.
        /// </summary>
        internal static string Options_OnlySelected {
            get {
                return ResourceManager.GetString("Options_OnlySelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Right.
        /// </summary>
        internal static string Options_Right {
            get {
                return ResourceManager.GetString("Options_Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à PDF Export Options.
        /// </summary>
        internal static string Options_Title {
            get {
                return ResourceManager.GetString("Options_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Top.
        /// </summary>
        internal static string Options_Top {
            get {
                return ResourceManager.GetString("Options_Top", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Unit.
        /// </summary>
        internal static string Options_Unit {
            get {
                return ResourceManager.GetString("Options_Unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Exporting diagram to PDF....
        /// </summary>
        internal static string Progress_Text {
            get {
                return ResourceManager.GetString("Progress_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à PDF Export....
        /// </summary>
        internal static string Progress_Title {
            get {
                return ResourceManager.GetString("Progress_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à PDF-Files (*.pdf)|*.pdf.
        /// </summary>
        internal static string SaveDialogFilter {
            get {
                return ResourceManager.GetString("SaveDialogFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à cm.
        /// </summary>
        internal static string Unit_CM {
            get {
                return ResourceManager.GetString("Unit_CM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à dots.
        /// </summary>
        internal static string Unit_Dots {
            get {
                return ResourceManager.GetString("Unit_Dots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à inch.
        /// </summary>
        internal static string Unit_Inch {
            get {
                return ResourceManager.GetString("Unit_Inch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à mm.
        /// </summary>
        internal static string Unit_MM {
            get {
                return ResourceManager.GetString("Unit_MM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à pixel.
        /// </summary>
        internal static string Unit_Pixel {
            get {
                return ResourceManager.GetString("Unit_Pixel", resourceCulture);
            }
        }
    }
}
