//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NReflect.Studio.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("TestCases")]
        public string TestCaseDirectory {
            get {
                return ((string)(this["TestCaseDirectory"]));
            }
            set {
                this["TestCaseDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point MainFormLocation {
            get {
                return ((global::System.Drawing.Point)(this["MainFormLocation"]));
            }
            set {
                this["MainFormLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("806, 473")]
        public global::System.Drawing.Size MainFormClientSize {
            get {
                return ((global::System.Drawing.Size)(this["MainFormClientSize"]));
            }
            set {
                this["MainFormClientSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Normal")]
        public global::System.Windows.Forms.FormWindowState MainFormWindowSate {
            get {
                return ((global::System.Windows.Forms.FormWindowState)(this["MainFormWindowSate"]));
            }
            set {
                this["MainFormWindowSate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Checked")]
        public global::System.Windows.Forms.CheckState ObjectComparePanelSynchronizeTrees {
            get {
                return ((global::System.Windows.Forms.CheckState)(this["ObjectComparePanelSynchronizeTrees"]));
            }
            set {
                this["ObjectComparePanelSynchronizeTrees"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Checked")]
        public global::System.Windows.Forms.CheckState ObjectComparePanelAutoResizeColumnsCheckState {
            get {
                return ((global::System.Windows.Forms.CheckState)(this["ObjectComparePanelAutoResizeColumnsCheckState"]));
            }
            set {
                this["ObjectComparePanelAutoResizeColumnsCheckState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string VisitorResultsDirectory {
            get {
                return ((string)(this["VisitorResultsDirectory"]));
            }
            set {
                this["VisitorResultsDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("264, 262")]
        public global::System.Drawing.Size RunVisitorsClientSize {
            get {
                return ((global::System.Drawing.Size)(this["RunVisitorsClientSize"]));
            }
            set {
                this["RunVisitorsClientSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool RunVisitorForAllTestCases {
            get {
                return ((bool)(this["RunVisitorForAllTestCases"]));
            }
            set {
                this["RunVisitorForAllTestCases"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool RunTestCaseBeforeVisitors {
            get {
                return ((bool)(this["RunTestCaseBeforeVisitors"]));
            }
            set {
                this["RunTestCaseBeforeVisitors"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ObjectPanelAutoResizeColumns {
            get {
                return ((bool)(this["ObjectPanelAutoResizeColumns"]));
            }
            set {
                this["ObjectPanelAutoResizeColumns"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ObjectPanelTypeVisible {
            get {
                return ((bool)(this["ObjectPanelTypeVisible"]));
            }
            set {
                this["ObjectPanelTypeVisible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string VisitorPanelVisitor {
            get {
                return ((string)(this["VisitorPanelVisitor"]));
            }
            set {
                this["VisitorPanelVisitor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Checked")]
        public global::System.Windows.Forms.CheckState MessagesPanelShowErrors {
            get {
                return ((global::System.Windows.Forms.CheckState)(this["MessagesPanelShowErrors"]));
            }
            set {
                this["MessagesPanelShowErrors"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Checked")]
        public global::System.Windows.Forms.CheckState MessagesPanelShowWarnings {
            get {
                return ((global::System.Windows.Forms.CheckState)(this["MessagesPanelShowWarnings"]));
            }
            set {
                this["MessagesPanelShowWarnings"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Checked")]
        public global::System.Windows.Forms.CheckState MessagesPanelShowInfos {
            get {
                return ((global::System.Windows.Forms.CheckState)(this["MessagesPanelShowInfos"]));
            }
            set {
                this["MessagesPanelShowInfos"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CompileFormSaveDir {
            get {
                return ((string)(this["CompileFormSaveDir"]));
            }
            set {
                this["CompileFormSaveDir"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CompileFormDllName {
            get {
                return ((string)(this["CompileFormDllName"]));
            }
            set {
                this["CompileFormDllName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("435, 291")]
        public global::System.Drawing.Size CompileFormClientSize {
            get {
                return ((global::System.Drawing.Size)(this["CompileFormClientSize"]));
            }
            set {
                this["CompileFormClientSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CompileFormAllTestCases {
            get {
                return ((bool)(this["CompileFormAllTestCases"]));
            }
            set {
                this["CompileFormAllTestCases"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CompileFormSingleDll {
            get {
                return ((bool)(this["CompileFormSingleDll"]));
            }
            set {
                this["CompileFormSingleDll"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool OptionsClearMessagesOnRun {
            get {
                return ((bool)(this["OptionsClearMessagesOnRun"]));
            }
            set {
                this["OptionsClearMessagesOnRun"] = value;
            }
        }
    }
}
